### ISSUE TITLE
Github link pointing to data set is broken.

### ISSUE THREAD

**Issue by shubajitsaha** [arijitx/BanglaNLP#5]
1. Github link is broken due to absent https prefix.
2. The href text does not point to what the kind of page the user is getting redirected.
3. Unnecessary spacing between the text and the github buttons.

**Comment by senbihan** [comment]
Closing this as PR is merged.

**Comment by arijitx** [comment]
Fix doesn't work due to how the domain name works, so preferable will a open in new tab.

**Comment by shubajitsaha** [comment]
Redirection on the same tab is working in local dev setup.Will adding target="_blank" in href solve the issue(This will open the page in a new tab)?

**Comment by arijitx** [comment]
Strange it works on the heroku build but not on the actual build. Actual one hosted in pythonaywhere only works when ctrl is pressed.

**Comment by shubajitsaha** [comment]
Issue is resolved in current build.
